version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - "weaveworks/wild-watermelon"
    # Only do security updates not version updates.
    open-pull-requests-limit: 0
