---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - gitops.weave.works
  resources:
  - gitopsclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - notification.toolkit.fluxcd.io
  resources:
  - alerts
  - providers
  verbs:
  - create
  - patch
- apiGroups:
  - pipelines.weave.works
  resources:
  - pipelines
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - pipelines.weave.works
  resources:
  - pipelines/finalizers
  verbs:
  - update
- apiGroups:
  - pipelines.weave.works
  resources:
  - pipelines/status
  verbs:
  - get
  - patch
  - update
