---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: pipeline-controller
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cluster.x-k8s.io
  resources:
  - clusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - gitops.weave.works
  resources:
  - gitopsclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - gitops.weave.works
  resources:
  - gitopsclusters/finalizers
  verbs:
  - update
- apiGroups:
  - gitops.weave.works
  resources:
  - gitopsclusters/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - pipelines.weave.works
  resources:
  - pipelines
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - pipelines.weave.works
  resources:
  - pipelines/finalizers
  verbs:
  - update
- apiGroups:
  - pipelines.weave.works
  resources:
  - pipelines/status
  verbs:
  - get
  - patch
  - update
