apiVersion: v2
name: pipeline-controller
description: Pipeline-controller Helm chart for Weave GitOps Enterprise
type: application
version: 0.15.0
appVersion: "v0.0.28"
dependencies:
  - name: pipeline-templates
    version: "0.1.0"
    repository: "file://../pipeline-templates"
    condition: templates.enabled
